import { useState } from "react";
import { relocateCities } from "../data/mockData";

type Message = { from: "ai" | "user"; text: string };

const questions = [
  "Hi, I'm here to help you find a home. What's your name?",
  "Nice to meet you. Which city are you moving to?",
  "Got it. What's your monthly budget, roughly?",
  "Last one, when are you hoping to move in?",
];

export default function Relocate() {
  const [consented, setConsented] = useState(false);
  const [step, setStep] = useState(0);
  const [input, setInput] = useState("");
  const [messages, setMessages] = useState<Message[]>([
    { from: "ai", text: questions[0] },
  ]);
  const [done, setDone] = useState(false);

  function submitAnswer(e: React.FormEvent) {
    e.preventDefault();
    if (!input.trim()) return;

    const answer = input.trim();
    const next = step + 1;
    const newMessages: Message[] = [...messages, { from: "user", text: answer }];

    if (next < questions.length) {
      newMessages.push({ from: "ai", text: questions[next] });
      setStep(next);
    } else {
      const city = messages.find((_, i) => i === 3)?.text ?? "your new city";
      newMessages.push({
        from: "ai",
        text: `Great, I'll start finding homes for you in ${city}. You'll see matches in Search shortly.`,
      });
      setDone(true);
    }

    setMessages(newMessages);
    setInput("");
  }

  if (!consented) {
    return (
      <div>
        <h1 className="font-display text-3xl font-semibold tracking-tight text-brand-ink">
          Relocate
        </h1>
        <p className="mt-1 text-brand-muted">
          Moving to a new country? Start with a quick guided chat.
        </p>

        <div className="mt-8 max-w-lg rounded-2xl border border-brand-border bg-brand-surface p-6">
          <p className="text-sm font-semibold text-brand-ink">
            Before we start
          </p>
          <ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-brand-muted">
            <li>This is a simple guided Q&amp;A, not a live phone call.</li>
            <li>Responses are generated by AI, clearly labeled as such.</li>
            <li>No real contact happens in this demo.</li>
            <li>Popular cities right now: {relocateCities.join(", ")}.</li>
          </ul>
          <label className="mt-4 flex items-start gap-2 text-sm text-brand-ink">
            <input
              type="checkbox"
              className="mt-0.5 accent-brand-blue"
              onChange={(e) => setConsented(e.target.checked)}
            />
            I understand this is an AI-guided demo, not a real call.
          </label>
          <button
            disabled={!consented}
            onClick={() => setConsented(true)}
            className="mt-4 rounded-lg bg-brand-blue px-4 py-2 text-sm font-semibold text-white transition-colors hover:bg-brand-blue-dark disabled:opacity-40"
          >
            Start guided chat
          </button>
        </div>
      </div>
    );
  }

  return (
    <div>
      <h1 className="font-display text-3xl font-semibold tracking-tight text-brand-ink">
        Relocate
      </h1>
      <p className="mt-1 text-brand-muted">
        This is a demo voice flow, simple guided questions only. No real call
        happens here.
      </p>

      <div className="mt-8 max-w-md rounded-2xl border border-brand-border bg-brand-surface p-5">
        <div className="flex flex-col gap-2">
          {messages.map((m, i) => (
            <div
              key={i}
              className={`rounded-lg px-3 py-2 text-sm ${
                m.from === "ai"
                  ? "border-l-2 border-brand-blue bg-white text-brand-ink"
                  : "ml-6 border-l-2 border-brand-border bg-white text-brand-ink"
              }`}
            >
              {m.text}
            </div>
          ))}
        </div>

        {!done ? (
          <form onSubmit={submitAnswer} className="mt-3 flex gap-2">
            <input
              autoFocus
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="🎙️ Hold to talk (type your answer)"
              className="flex-1 rounded-lg border border-brand-border bg-white px-3 py-2 text-sm outline-none focus:border-brand-blue"
            />
            <button
              type="submit"
              className="rounded-lg bg-brand-blue px-4 py-2 text-sm font-semibold text-white hover:bg-brand-blue-dark"
            >
              Send
            </button>
          </form>
        ) : (
          <p className="mt-3 text-xs text-brand-muted">
            Chat complete. In the real product this hands off into Search
            with your answers pre-filled.
          </p>
        )}
      </div>
    </div>
  );
}
